title: 'GitHub setup '
description: Addin to my IPhone 11
template:
  repo: github-setup-template
  name: github-setup
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
